name: Docker Image CI

on:
  push:
    branches: [ 0.8.7-updates ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag micboard:$(date +%s)